### ISSUE TITLE
www-prefix in URL field causes 400 when trying to save profile changes

### ISSUE THREAD

**Issue by RobertWalter83** [basti1302/elm-lang-de#20]
I typed "www.digital-ember.com" into the URL field on the "edit profile" page, which let to a 400 bad request trying to save my changes:
![image](https://cloud.githubusercontent.com/assets/5462981/23788445/c0cfbd52-0576-11e7-9f86-55997455084d.png)

**Comment by basti1302** [comment]
Thanks a lot for the report! I actually think that it is the missing `http://`/`https://` prefix which causes the problem. I have not investigated it yet, though.

Maybe related: if you somehow manage to put a URL without a protocol like `http` into the database, the link on the profile page is wrong. You can see this at https://elm-lang.de/#developers/klaftertief. @klaftertief's profile has such a URL and the link on his profile page goes to `https://elm-lang.de/klaftertief.de`. (I guess the URL was automatically imported from his public GitHub profile data when creating the account).

**Comment by basti1302** [comment]
the app now prepends "http://" automatically before validating the URL, if necessary.

**Comment by RobertWalter83** [comment]
Sweet.
