### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by basti1302** [basti1302/elm-lang-de#7]
Hier schon mal ein paar unsortierte TODOs zum produktiven Deployment, alles natürlich unter Vorbehalt, dass wir darüber ggf. noch mal diskutieren wollen:

* Digital Ocean Droplet aufsetzen
* Let's Encrypt Cert besorgen
* Drei Docker Container erstellen:
    * elm-lang-de-db: PostgreSQL
    * elm-lang-de-app: Die Haskell-/Servant Anwendung inkl. der Front End Assets
    * elm-lang-de-nginx: SSL-Terminierung
    * Ich habe bei playtimepal.com schon eine Vorlage für diese Container inkl. docker-compose.yml..., könnte man wahrscheinlich relativ flott für elm-lang-de anpassen.
* Domain auf Digital Ocean Droplet mappen.

**Comment by basti1302** [comment]
done

**Comment by dennisreimann** [comment]
Sehr cool! 🎉
